stages:
  - build
  - deploy

variables:
  PAPER: 'proposal'


prgbib_pdf:
  stage: build
  tags:
    - docker
  image: kmindi/latex-docker  # use a Docker image for LaTeX from https://hub.docker.com/
  script:
    - rm -f *.bbl *.log *.out
    - pdflatex proposal.tex
    - biber proposal
    - pdflatex proposal.tex
    - pdflatex proposal.tex

  artifacts:
    paths:
      - $PAPER.pdf

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp $PAPER.pdf .public
    - cp sup.pdf .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

